[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322

[auth]
site_url = "relay://auth-callback"
additional_redirect_urls = ["relay://auth-callback"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
